### ISSUE TITLE
Numpy issue np.amin(boosts_heights)

### ISSUE THREAD

**Issue by asdat3** [Sebastianaplikacja/thorami-bot#1]
```
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    bot.initialize_agent()
  File "C:\Users\quent\OneDrive\Desktop\DONTDELETE\rl\source\thorami-bot-main\nexto.py", line 52, in initialize_agent
    self.obs_builder = NextoObsBuilder(self.total_players, self.total_boosts, self.buffer_cursor)
  File "C:\Users\quent\OneDrive\Desktop\DONTDELETE\rl\source\thorami-bot-main\nexto_obs.py", line 188, in __init__
    boosts_heights_min = np.amin(boosts_heights)
  File "<__array_function__ internals>", line 200, in amin
  File "C:\Users\quent\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "C:\Users\quent\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

Couldnt find the issue myself, help would be insane

**Comment by psxjtwr01** [comment]
Use RLmarlbot instead its 10x better has multiple bots and is super easy to use 😄 
@asdat3 
> ```
> Traceback (most recent call last):
>   File "main.py", line 43, in <module>
>     bot.initialize_agent()
>   File "C:\Users\quent\OneDrive\Desktop\DONTDELETE\rl\source\thorami-bot-main\nexto.py", line 52, in initialize_agent
>     self.obs_builder = NextoObsBuilder(self.total_players, self.total_boosts, self.buffer_cursor)
>   File "C:\Users\quent\OneDrive\Desktop\DONTDELETE\rl\source\thorami-bot-main\nexto_obs.py", line 188, in __init__
>     boosts_heights_min = np.amin(boosts_heights)
>   File "<__array_function__ internals>", line 200, in amin
>   File "C:\Users\quent\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amin
>     return _wrapreduction(a, np.minimum, 'min', axis, None, out,
>   File "C:\Users\quent\AppData\Local\Programs\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
>     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> ValueError: zero-size array to reduction operation minimum which has no identity
> ```
> 
> Couldnt find the issue myself, help would be insane
